name: "[CI] Verify Tests Pass"

on:
  push:
    branches:
      - main

job:
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Deps
        run: npm ci
        working-directory: frontend

      - name: Run Tests
        run: npm t
        working-directory: frontend

  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Deps
        run: npm ci
        working-directory: backend

      - name: Run Tests
        run: npm t
        working-directory: backend
